name: Deploy to Server

on:
  push:
    branches: [ main ] # تأكد واش البرانش سميتها main أو master

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Docker
        run: |
           docker-compose down
           docker-compose up -d --build